### ISSUE TITLE
Error: 'git clone' failed with status 128

### ISSUE THREAD

**Issue by donglegend** [flipxfx/download-git-repo#19]
why?

**Comment by jzz4012650** [comment]
have the same problem

**Comment by flipxfx** [comment]
Can I get some more info on when this happens?

**Comment by kuangcaibao** [comment]
I use tfs as my code server, a project url like "http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template"

git clone cli works fine in git bash

```
$ git clone xxx
```

but, this does not work

```
download("http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template", dname, {clone: true}, function(err) {
    
    spinner.stop();
    if(err) {

      console.log("Failed to download repo: " + err.message.trim());
    }
    else {

      console.log("Download Success.");
    }
  })
```

Error Info:

```
Failed to download repo: 'git clone' failed with status 128
```

**Comment by twehrmaker** [comment]
Thats because of the colon in the url for the port. Thus the port will be recognized as owner. Am currently facing the same issue.

**Comment by flipxfx** [comment]
The issue here really isn't the colon in the url for the port. The regex correctly captures all colons up until the last one that separates the origin from the repo. The real issue is that your url isn't following a "user/repo" style url. For example if your url was the following, then it would work correctly:
```
http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template:username/reponame
```

You might be able to side step this issue by using the following (note this would only work for clone):
```
http://192.168.0.53:9471/tdx/TdxModules:_git/tdx-template
```

Which would send the following url to by cloned:
```
http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template.git
```

Let me know if this works for you guys.

**Comment by kuangcaibao** [comment]
This does not work for me. 

It seems the git repo url in team foundation server does not like xxx.git

```
$ git clone http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template.git
Cloning into 'tdx-template'...
remote: TF200016: 以下项目不存在: tdx-template.git。请确保项目名称正确并且该项目位于指定的 Team Foundation Server 上。
fatal: unable to access 'http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template.git/': The requested URL returned error: 500
```

Meanwhile, _git is not an account, the following works for me:

```
const clone = require("git-clone");
...
clone("http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template", dname, {clone: true}, function(err) {
  ...
}
```

Thanks

**Comment by flipxfx** [comment]
Then maybe to get around something like this we can add another repo type. Current only GitHub, GitLab and Bitbucket are supported. Maybe we can have something like "Direct" where it wouldn't try to normalize the string and just send it directly to the clone or download. You won't get the niceties of shorthand, but it would at least help cover more hosts and would be pretty straightforward if using clone. Something like: 
```js
download('direct:http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template', 'test/tmp', { clone: true }, function (err) {
  console.log(err ? 'Error' : 'Success')
})
```

If you wanted to use download you would need something more like the following that matches whatever your git host has for downloading the zip version:
```js
download('direct:http://192.168.0.53:9471/tdx/TdxModules/_git/tdx-template/archive/master.zip', 'test/tmp', function (err) {
  console.log(err ? 'Error' : 'Success')
})
```

Would `direct` make sense if we went this route? Or maybe `other` or`url`?

**Comment by kuangcaibao** [comment]
`direct` will be cool

**Comment by flipxfx** [comment]
@donglegend @twehrmaker @jzz4012650 what you guys think?

**Comment by deniszavadskiy** [comment]
Fix this issue as soon as possible please.
The problem is that on windows path couldn't contain colons 
C:\Users\IEUser\.vue-templates\gitlab:gitlab.com:name - it is not valid path

The problem should be solved on generating dest variable step

**Comment by flipxfx** [comment]
Can you try with pull request #23? I asked for feedback but didn’t get any.

**Comment by JulienPalard** [comment]
We're facing the same bug with `git@our_gitlab_instance.our_domain:project_group/project.git`, the regex `var regex = /^((github|gitlab|bitbucket):)?((.+):)?([^/]+)\/([^#]+)(#(.+))?$/` obviously don't match it and fallback on github. Why not trusting the user when the shortcut-regex don't match instead of fallbacking on github?

**Comment by JulienPalard** [comment]
The direct option make no sense to me, implementing hardcoded shortcuts are almost OK, but implementing a whole new syntaxe to bypass the shortcuts is not.

**Comment by flipxfx** [comment]
Well the whole idea of this repo is based on shortcuts, so if you're using it just to download git repos then you've got the wrong repo. Just use download or git-clone directly. I originally built this for vue-cli to support other hosts like gitlab and bitbucket, but I think anything outside of that I would prefer to use a `direct` option so we don't mess up the shortcuts and it would be more explicit. All you have to do is `direct:whatevertheheck.com/you/want/here`.

**Comment by JulienPalard** [comment]
I was in fact using vue-cli, but with a private repo in a private gitlab instance, and got the "failed with status 128" so I inspected (used strace) and found that download-git-repo was hitting github instead of my instance, so I went to open an issue, and found this one.

From a vue-cli point of view, using "direct:" does not make sense, we just want to use our repo URL, especially if it's a valid one (not a shortcut).

**Comment by flipxfx** [comment]
The vue-cli was first built with only github shortcut support so I think that point of view isn’t accurate. I’m just not sure how to handle something like that because it falls back to github. I don’t know what your “valid” url looks like and it can vary pretty wildly and be tricky to implement. If you can come up with a clean and reliable way then feel free to open a pull request. I just don’t want to mess up a current functionality for a github repo or no way to force direct. 

For example you may want intranet/repo or https://mygitlab.com:flipxfx/download-git-repo-fixture. How do you decide if these are direct or using shortcuts?

**Comment by kavinforever** [comment]
@flipxfx Hi,i am running the direct branch, but the question is the same .
```js
 download('direct:http://gitlab.aaa.com/ADC-FE/gladder.git#develop', prjPath, { clone: true },(err) => {
```
![image](https://user-images.githubusercontent.com/9795441/33828308-882bb32a-dea6-11e7-8632-a25688e69433.png)

**Comment by flipxfx** [comment]
@kavinforever if you are using `direct` then you can't use #develop for shortcuts. You have to give it the exact path. But if you're using you're own Gitlab then you should be able to use something like `http://gitlab.aaa.com:ADC-FE/gladder#develop` instead of using `direct`.

**Comment by kavinforever** [comment]
it seems to me that the status 128 is caused by the private repo's authority setting. i am setting this repo's Visibility Level to Public(The project can be cloned without any authentication.) && using the following code. it works fine.

```js
const gitClone = require('git-clone');
gitClone('http://gitlab.alibaba-inc.com/ADC-FE/gladder.git', prjPath, 
{checkout: 'develop'}, (err) => {
```

**Comment by flipxfx** [comment]
Yes, if the repo is private then you need to have your SSH keys setup and use clone.

**Comment by n0tion** [comment]
@flipxfx I'm receiving the same error code but from a github private repo. I generated my ssh key pair and added. I'm able to clone the private repo from the git cli and sourcetree. How can I have them be recognized from within my app?

**Comment by huangming1994** [comment]
still not working, got the same issue.

**Comment by timrijkse** [comment]
Same here, any idea on how to test ssh keys in combination with download-git-repo?

**Comment by dooboolab** [comment]
I am also having same problem!

**Comment by deniszavadskiy** [comment]
for ssh try to use (gitlab example)

git.yourdomain.com:group/project-name

and that all, without .git at the end git+ssh:// on start

**Comment by dooboolab** [comment]
@deniszavadskiy 
if https doesn't work and only work for ssh, users can't download from my repository when I created cli tool to download the boilerplate. Am I right?

**Comment by deniszavadskiy** [comment]
@dooboolab read the example above, I added the https syntax that I found yesterday

**Comment by dooboolab** [comment]
@deniszavadskiy 
Sorry I am confused.
If my repository is `https://github.com/dooboolab/react-native-typescript-starter` this one.
How would my url be?

I've tried `github:git.github.com:dooboolab/react-typescript-webpack-starter` and some other things but have no idea..

**Comment by dooboolab** [comment]
@deniszavadskiy 
I've tried that already but still the same..

![image](https://user-images.githubusercontent.com/27461460/36074444-4dd8f936-0f83-11e8-855d-503b33e779fb.png)

**Comment by flipxfx** [comment]
Seems like this issue is bouncing around. @dooboolab your issue is that it should be just `dooboolab/react-typescript-webpack-starter`, it's public and GitHub. The clone option is for private repos so it will try to use gitclone and use your SSH keys. I think these are either syntax errors, problems with SSH, or https://github.com/jaz303/git-clone . Haven't been able to reproduce these errors so I can't debug them. I've tried private repos on GitLab, GitHub and Bitbucket using https://github.com/flipxfx/download-git-repo-cli with the clone option and it works with my SSH key setup. If anyone that has this error can find that it's actually an issue with the repo, please let me know.

For the other issue of allowing `direct` full urls, I'll leave that discussion in PR #23 if anyone wants to chime in.
