### ISSUE TITLE
not support http mode

### ISSUE THREAD

**Issue by kospot** [flipxfx/download-git-repo#20]
I use the private repository, found that the function of normalize seems not work correctly.
`
normalize('http://192.xxx.xx.xx/test/vue-template-test')
`
the result is
`
{"type":"github","origin":"github.com","owner":"http:","name":"/192.xxx.xx.xx/test/vue-template-test","checkout":"master"}
`

It will fail by git clone

**Comment by flipxfx** [comment]
That looks like incorrect syntax. If you are hosting GitHub and want master branch it would be
`http://192.xxx.xx.xx:test/vue-template-test`

If you hosting GitLab it would be
`gitlab:http://192.xxx.xx.xx:test/vue-template-test`

If you are using git clone because it's private then you don't need the `gitlab` part like
`http://192.xxx.xx.xx:test/vue-template-test`

**Comment by flipxfx** [comment]
Please see #19 also if the above doesn't work for you.

**Comment by kospot** [comment]
thanks，I find the reason. 
for the vue-cli package, it's dist file path include the symbol ':' (window os), that make download fail

**Comment by flipxfx** [comment]
closing, #19 may help
